version: '3.8'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    
    container_name: ticketFee
    ports:
      - "8000:8000"

    tty: true

    volumes:
      - ./src:/app